#######################################################################################################
#
# Esse é um plugin gratuito feito por: iMax, caso precise de ajuda com o plugin,
# me chame discord: https://discord.com/users/425360819224576011
#
# Vamos fazer o seguinte? Eu te ajudo com esse plugin e você me ajuda entrando em meu discord!
# https://discord.gg/PNBNKXSGpG
#
#######################################################################################################

#
# /ban - im.ban ou im.ban.solicitacao
# /mute - im.mute
# /kick - im.kick
# /unban - im.unban
# /unmute - im.unmute
# /pver - im.pver
#
# Para banir em silêncio - im.supressban
# Para kickar em silêncio - im.supresskick
# Para mutar em silêncio - im.supressmute
# Para banir o IP - im.ipban
#

# Validação do bot para notificação no discord
Bot:
  Ativo: true
  Token: TOKEN
  Guild: 000000000000
  BanChannel: 000000000000
  SolicitacaoChannel: 000000000000

Icons:
  Confirmar:
    ICON: '      &2[V]'
    TEXT: '&aClique aqui para punir esse jogador.'
  Cancelar:
    ICON: '      &c[X]'
    TEXT: '&cClique aqui para cancelar a punição desse jogador.'
  SilenceBan:
    ICON: '      &e[S]'
    TEXT: '§eClique aqui para punir o jogador em silêncio.'
  IPBan:
    ICON: '      &4[!]'
    TEXT: '§cClique aqui para banir o IP do jogador.'

# Sistema de armazenamento de dados
MySQL:
  Ativo: false
  DataBase: sv
  User: localhost
  IP: 127.0.0.0
  Pass: root
  Port: 3306

# Mensagem do discord, embed embreve
Bot-Mensagens:
  Solicitacao:
    Titulo: 'Titulo aqui'
  Ban:
    Titulo: 'Titulo aqui'

# Usa o bungeecord? ative essa função e coloque o IMBansBungeeCord em na sua bungee
# Plugin disponível em nosso discord
BungeeCord:
  Ativo: false

# Notificações ativas?
Mensagens:
  Anunciar-All: true
  Ban: true
  Mute: true
  unMute: true
  unBan: true
  Kick: true

# Servidores caso use discord
Servidores:
  Factions:
    Nome: 'Factions'
    Server: 'factions'
    Atual: true
  Lobby:
    Nome: 'Lobby'
    Server: 'lobby'
    Atual: false

Commands-Blocked-Mute:
  - '/g'
  - '/tell'
# %user% para o jogador
# %motivo% para o motivo
# %author% para o staffer
# %prova% para a prova
# %tempo% para o tempo
# %server% para o server
Server-Mensagens:
  Ban:
    - ''
    - '           &6&lBAN'
    - '     &fO Jogador %user% foi banido.'
    - '     &fMotivo: &7 %motivo%'
    - '     &fAuthor: &7 %author%'
    - '     &fProva: &7 %prova%'
    - '     &fExpira em: &c%tempo%'
    - ''
  Ban-Perma:
    - ''
    - '           &6&lBAN'
    - '     &fO Jogador %user%  foi permanentemente banido.'
    - '     &fMotivo: &7 %motivo%'
    - '     &fAuthor: &7 %author%'
    - '     &fProva: &7 %prova%'
    - ''
  Mute:
    - ''
    - '           &6&lMUTE'
    - '     &fO Jogador %user%  foi permanentemente mutado.'
    - '     &fMotivo: &7 %motivo%'
    - '     &fAuthor: &7 %author%'
    - '     &fProva: &7 %prova%'
    - '     &fExpira em: &c%tempo%'
    - ''
  Mute-Perma:
    - ''
    - '           &6&lMUTE'
    - '     &fO Jogador %user%  foi mutado.'
    - '     &fMotivo: &7 %motivo%'
    - '     &fAuthor: &7 %author%'
    - '     &fProva: &7 %prova%'
    - ''
  Kick:
    - ''
    - '           &6&lKICK"'
    - '     &fO Jogador %user%  foi kick.'
    - '     &fMotivo: &7 %motivo%'
    - '     &fAuthor: &7 %author%'
    - ''
  unMute:
    - ''
    - '           &6&lUNMUTE'
    - '     &fO Jogador %user% foi desmutado.'
    - ''
  unBan:
    - ''
    - '           &6&lUNBAN'
    - '     &fO Jogador %user% foi desbanido.'
    - ''
  Tela-Ban-Perma:
    - ''
    - '&c&lBANIDO!'
    - '     &fVocê foi permanentemente banido do servidor!'
    - '     &fAuthor: %author%'
    - '     &fMotivo: %motivo%'
    - ''
  Tela-Ban:
    - ''
    - '&c&lBANIDO!'
    - '     &fVocê foi banido do servidor!'
    - '     &fAuthor: %author%'
    - '     &fMotivo: %motivo%'
    - '     &fExpira em: %tempo%'
    - ''
  Tela-Kick:
    - ''
    - '&6&lKICKADO!'
    - '     &fVocê foi kickado do servidor!'
    - '     &fAuthor: %author%'
    - '     &fMotivo: %motivo%'
    - ''
  MutadoMSG: '&cMutado por: %author% expira em %tempo%'
  MutadoPermaMSG: '&cPermanentemente mutado por: %author%'
